spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  cloud:
    stream:
      bindings:
        handleRun-in-0:
          binder: rabbit
          destination: cse-idcc-launch-task

cse-cc-runner:
  binding:
    destination: cse-request

minio-adapter:
  url: http://minio:9000/
  base-path: /CSE/D2CC/
  bucket: gridcapa
  access-key: gridcapa
  secret-key: gridcapa

cse-adapter:
  target-process: IDCC
  target-ch-fs-location: /path/to/fs/location
  target-ch-minio-location: /path/to/minio/location