spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  cloud:
    stream:
      bindings:
        handleRun-in-0:
          binder: rabbit
          destination: cse-idcc-launch-task

cse-cc-runner:
  binding:
    destination: cse-request

cse-adapter:
  target-process: IDCC